#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

PROG="/usr/bin/cups-mdns"
CONFIG="cups-mdns"

start_service() {
	local enabled host port hostname interval timeout debug loopback
	config_load "$CONFIG"
	config_get_bool enabled config enabled 0

	[ "$enabled" = "0" ] && {
		logger -t cups-mdns "Service disabled"
		return
	}

	config_get host config cups_host ""

	[ -z "$host" ] && {
		logger -t cups-mdns "No CUPS host configured, not starting"
		return
	}
	config_get port config cups_port ""
	config_get hostname config hostname "cups-proxy"
	config_get interval config poll_interval "360"
	config_get timeout config timeout "5"
	config_get_bool debug config debug "0"
	config_get_bool loopback config loopback "0"
	config_get bind_interface config bind_interface ""

	procd_open_service "cups-mdns" "/etc/init.d/cups-mdns"
	procd_open_instance
	procd_set_param command "$PROG" \
		--host "$host" \
		--port "$port" \
		--hostname "$hostname" \
		--interval "$interval" \
		--timeout "$timeout"
	[ "$debug" = "1" ] && procd_append_param command --debug
	[ "$loopback" = "1" ] && procd_append_param command --loopback
	[ -n "$bind_interface" ] && procd_append_param command --iface "$bind_interface"
	procd_set_param respawn 3600 1 10
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
	procd_close_service
}

reload_service() {
	restart
}

service_triggers() {
	procd_open_trigger
	procd_add_config_trigger "config.change" "$CONFIG" /etc/init.d/$CONFIG reload
	procd_close_trigger
}
